#!/usr/bin/env bash
#
# Checks whether any textual files contain CRLF (DOS-style) endings.
# Much the same as trailing whitespace.

# Whether to fix to UNIX-style endings.
FIX=0
if [[ $1 == "fix" ]]; then
    FIX=1
fi

# Directories under scrutiny
DIRS=("core" "bin" "examples")

# Counter to keep track of number of files with trailing white space.
ERRORS=0


PATTERNS=("*.ml" "*.mli" "*.mly" "*.mll" "*.py" "*.pl" "*.html" "*.js"\
          "*.txt" "*.links" "*.css" "*.sh" "*.el" "*.vim" "*.opam"\
          "dune-project" "dune")

SEP=" -o -name "
FIND_STR="$( printf "${SEP}\"%s\"" "${PATTERNS[@]}" )"
FIND_STR="${FIND_STR:${#SEP}}"
FIND_STR="-name $FIND_STR"
echo ${FIND_STR}
PATTERN=$'\x0d' # Carriage return literal


for dir in ${DIRS[@]}; do
    for file in $(eval "find \""$dir"\" -type f \( ${FIND_STR} \) \
      -exec grep -IUl \"$PATTERN\" {} \;"); do
          echo -n "$file"
          if [[ $FIX -eq 1 ]]; then
              echo -n "..."
              sed -i "s/$PATTERN//" $file
              if [[ $? -eq 0 ]]; then
                  echo " FIXED."
              else
                  echo " FAILED."
                  ERRORS=$((ERRORS+1))
              fi
          else
              echo ""
              ERRORS=$((ERRORS+1))
          fi
    done
done

if [[ $ERRORS -ne 0 ]]; then
    exit 1
else
    exit 0
fi
