#!/bin/bash

# check files to make sure they're all accounted for
checkdir=.check
errorCode=0

# create dir for checking files
if [ ! -d $checkdir ]; then
  mkdir $checkdir
fi

# list sorted files in directory .
find . | sed -e 's/^\.\///g' \
| grep -E '^[^\.](/[^\.]|[^/])+$' | sort -b > $checkdir/all

# list sorted files taken from file MANIFEST 
cat MANIFEST | sed 's/ *#.*$//g' | grep -E '^[^[:space:]]' | sed -r 's/\/[[:space:]]*$//g' | sort -b > $checkdir/manifest

# list sorted files taken from file COMANIFEST 
cat COMANIFEST | sed 's/ *#.*$//g' | grep -E '^[^[:space:]]' | sed -r 's/\/[[:space:]]*$//g' | sort -b > $checkdir/comanifest

# extras in MANIFEST but not actually present in the directory structure
diff $checkdir/manifest $checkdir/all | grep '^<' | sed 's/^< //g' > $checkdir/manifestextras

# extras in COMANIFEST but not actually present in the directory structure
diff $checkdir/comanifest $checkdir/all | grep '^<' | sed 's/^< //g' > $checkdir/comanifestextras

# extras in the directory structure but not in MANIFEST or COMANIFEST
diff $checkdir/manifest $checkdir/all | grep '^>' | sed 's/^> //g' \
| diff $checkdir/comanifest - | grep '^>' | sed 's/^> //g' > $checkdir/allextras

# report errors
if [ -s $checkdir/allextras ]; then
  echo "Error: files missing from MANIFEST or COMANIFEST"
  echo
  cat $checkdir/allextras
  errorCode=1
fi

if [ -s $checkdir/manifestextras ]; then
  echo "Error: non-existant files in MANIFEST"
  echo
  cat $checkdir/manifestextras
  errorCode=1
fi

if [ -s $checkdir/comanifestextras ]; then
  echo "Error: non-existant files in COMANIFEST"
  echo
  cat $checkdir/comanifestextras
  errorCode=1
fi

# return error code
exit $errorCode
