-include ./Makefile.config


LINKSBASEMAKEFILE = ./Makefile.shared
include $(LINKSBASEMAKEFILE)

SOURCES :=	$(SOURCES)			\
				unitTestsJson.ml	\
				unitTests.ml 		\

# because we update packs we need to ensure REAL_OCAMLFIND is undefined
undefine REAL_OCAMLFIND
PACKS :=	$(PACKS) oUnit

RESULT  = linksTests

include $(OCAMLMAKEFILE)

