-include ./Makefile.config

LINKSBASEMAKEFILE = ./Makefile.shared
include $(LINKSBASEMAKEFILE)

SOURCES :=	$(SOURCES)			\
				unitTestsJson.ml	\
				unitTests.ml 		\

PACKS :=	$(PACKS) oUnit

RESULT  = linksTests

include $(OCAMLMAKEFILE)

