# To enable the database DB set the appropriate *_LIBDIR variable below
# to the path of the OCaml bindings for that database.

# SQL Lite
#SQLITE_LIBDIR=/opt/ocaml-310/lib/site-lib/sqlite3

# MySQL
#MYSQL_LIBDIR=

# PostgreSQL
POSTGRESQL_LIBDIR=/opt/ocaml-310/lib/site-lib/postgresql

# EXTRA_LIBDIRS gives the paths of any additional libraries that need to be
# linked for your particular database library to work.
#   (e.g. /usr/local/mysql/lib)
EXTRA_LIBDIRS=