#!/bin/bash

make test-raw | perl -lne '($f) = /(\d+) failures/; print "$f failures" if ($f > 0); $F += $f; ($s) = /(\d+) successes/; $S += $s; END { print "$F total failures\n$S total successes\n"}'
