#!/bin/bash

make unit-tests

if [ $? -eq 0 ]; then
	clear
	echo "Compilation was successful, running tests."
	./linksTests -runner sequential
	rm ./linksTests
else
	echo "Build failed, not running tests."
fi

