#!/bin/bash

# If you modify the behaviour of this file please remember to update the
# relevant wiki page:
#
# https://github.com/links-lang/links/wiki/Running-the-test-suite

ret=0

if [[ $1 != "db-only" ]]; then
    for i in tests/*.tests; do
        cmnd="./test-harness $i"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [ $ret_code != 0 ]; then
            ret=1
        fi
    done
fi

if [[ $1 != "no-db" ]]; then
    for s in tests/database/*.sql; do
        cmnd="psql -v ON_ERROR_STOP=1 -q -d links -f $s"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [ $ret_code != 0 ]; then
            echo "FAILED DATABASE PREPARATION $s"
            ret=1
        fi
    done

    for t in tests/database/*.links; do
        cmnd="./links --config=tests/database/config $t"
        echo cmnd=$cmnd
        eval $cmnd
        ret_code=$?
        if [ $ret_code != 0 ]; then
            echo "FAILED TEST $t"
            ret=1
        fi
    done
fi

exit $ret
