#!/usr/bin/env python3

links = './links'

import sys, re, time
import concurrent.futures, threading, multiprocessing
from os import path
from subprocess import Popen, PIPE

successes = failures = ignored = 0
TIMEOUT = 15 # seconds before a test is timed out.

the_lock = threading.Lock()

def FAIL(name, msg):
    return ('  error: %s' % name,'      (%s)' % msg)

# must only be called while having the lock
def OK(name):
    global successes
    successes+=1
    print(' SUCCESS: %s' % name)

def parse(stream):
    """Read test information separated by blank lines.  The first line
    is the test name; the second is the test code; the remaining lines
    are auxiliary options"""
    def tests():
        tests = []
        for line in stream.readlines():
            if not str.strip(line) and tests[-1]:
                yield tests
                tests = []
            else:
                tests.append(line)
        yield tests
    for test in tests():
        if not test:
            print('WARNING: empty test', file=sys.stderr)
        else:
            name = str.strip(test.pop(0))
            code = str.strip(test.pop(0))
            opts = dict([str.split(str.rstrip(line), ' : ', 1) for line in test])
            yield name, code, opts

# Lock not required for calling
def check_expected(name, item, got, expected, errors):
    """Check some data against an expected value or predicate.  If it
    matches, return True.  Otherwise, display an error and return
    False.
    """
    got, expected = got.rstrip(), expected.rstrip()
    if expected.startswith('@'):
        if not re.match(expected[1:], got, re.DOTALL):
            errors.append(FAIL(name, "Unexpected %s: expected `%s' (regex); got `%s'" %
                               (item, expected[1:], got)))
            return False
        else:
            return True
    elif expected != got:
        errors.append(FAIL(name, "Unexpected %s:\nexpected `%s';\n     got `%s'" % (item, expected, got)))
        return False
    else:
        return True

def evaluate(name, code, config_file, stdout='', stderr='', exit = '0', env = None, filemode='', args='', ignore = None):
    arg_array = str.split(args)
    global failures

    if config_file != None:
        for arg in arg_array:
            if arg.startswith("--config"):
                print(
                    "FAILURE: Test \"%s\" comes with an args entry to specify the config file," % name +
                    " but a config file was also passed as a command-line argument to the test harness" )
                failures += 1
                return

        arg_array += ["--config=" + config_file]

    if not filemode.startswith('true'):
        arg_array += ["-e"]

    proc = Popen([links] + arg_array + [code], stdout=PIPE, stderr=PIPE, env=env)

    passed = True
    errors = []
    for i in range(0, TIMEOUT*100):
        rc = proc.poll()
        if rc != None:
            passed &= check_expected(name, 'return code', str(rc), exit, errors)
            passed &= check_expected(name, 'stdout', proc.stdout.read().decode('ascii'), stdout, errors)
            passed &= check_expected(name, 'stderr', str(proc.stderr.read().decode('ascii')), stderr, errors)
            if passed:
                with the_lock:
                    OK(name)
            else:
                if ignore != None:
                    global ignored
                    with the_lock:
                        ignored += 1
                        print('?IGNORED: %s (%s)' % (name, ignore))
                else:
                    with the_lock:
                        failures += 1
                        print('!FAILURE: %s' % name)
                        for i, j in errors:
                            print(i)
                            print(j)
            return
        else:
            time.sleep(0.01)

    with the_lock:
        failures += 1
        print('!FAILURE: %s [TIMED OUT]' % name)

def main():
    config_file = None

    if len(sys.argv) == 3:
        filename = sys.argv[1]
        config_file =  sys.argv[2]
    elif len(sys.argv) == 2:
        filename = sys.argv[1]
    else:
        raise SystemExit('Usage: run <test file> [<links config file>]')

    if path.exists(filename + ".config"):
        config_file = filename + ".config"

    cpus=multiprocessing.cpu_count()
    tp = concurrent.futures.ThreadPoolExecutor(max_workers=cpus)
    for name, code, opts in parse(open(filename, 'r')):
        # enqueues execution of
        # evaluate(name, code, config_file, **opts)
        # in the thread pool
        tp.submit(evaluate, name, code, config_file, **opts)

    # Wait for all jobs to finish
    tp.shutdown(wait=True)

    print("%d failures (+%d ignored)\n%d successes\n" % (failures, ignored, successes))
    if failures > 0:
        sys.exit(1)
    else:
        sys.exit(0)

if __name__ == '__main__':
    main()
