OCAMLMAKEFILE = ../../OCamlMakefile

AUXLIB_DIRS = 
OCAMLOPT := ocamlopt.opt
OCAMLC := ocamlc.opt
OCAMLDEP := ocamldep

OCAMLFLAGS=-w Ae

SOURCES = util.ml type.ml show.ml bounded.ml enum.ml pickle.ml primitives.ml

LIBS    = nums
RESULT  = deriving
CLIBS 	= 

INCDIRS = $(AUXLIB_DIRS)
LIBDIRS = $(AUXLIB_DIRS)

DOC_FILES=

include $(OCAMLMAKEFILE)
