.TH "cduce_mktop" "1" 
.SH "NAME" 
cduce_mktop \(em Produce a customized CDuce toplevel/compiler. 
.SH "SYNOPSIS" 
.PP 
\fBcduce_mktop\fR [\fB\fBtarget\fP\fP]  [\fB\fBprimitive file\fP\fP]  
.SH "Description" 
.PP 
See the CDuce users' manual: 
 
\fBhttp://www.cduce.org/manual_interfacewithocaml.html#link\fP. 
.SH "Author" 
.PP 
Alain Frisch <Alain.Frisch@ens.fr>. 
.\" created by instant / docbook-to-man, Fri 08 Jul 2005, 11:52 
