.TH "cduce" "1" 
.SH "NAME" 
cduce \(em The CDuce compiler/interpreter/toplevel 
.SH "SYNOPSIS" 
.PP 
\fBcduce\fR [  \fBOPTIONS\fP \&...]  [\fB\-\-arg \fBargument\fP\fP \&...]  
.PP 
\fBcduce\fR [  \fBOPTIONS\fP \&...]  [\fB \fBfile.cd\fP | \-\-stdin \fP]  [\fB\-\-arg \fBargument\fP\fP \&...]  
.PP 
\fBcduce \-\-compile\fR [  \fBOPTIONS\fP \&...]  [ \fB\fBfile.cd\fP\fP ]  
.PP 
\fBcduce \-\-run\fR [  \fBOPTIONS\fP \&...]  [  \fB\fBfile.cdo\fP\fP \&...]  [\fB\-\-arg \fBargument\fP\fP \&...]  
.SH "Description" 
.PP 
See the CDuce users' manual: 
 
\fBhttp://www.cduce.org/manual_interpreter.html\fP. 
.SH "Reporting bugs" 
.PP 
Report bugs to devel@cduce.org. 
.SH "See also" 
.PP 
A complete documentation, reference manual, tutorial, technical articles on 
implementation and theoretical issues, benchmarks, source code, mailing lists 
and forums can be found on the \fICDuce\fP website: 
\fBhttp://www.cduce.org/\fP. 
.SH "Authors" 
.PP 
Alain Frisch <Alain.Frisch@ens.fr>. Small contributions by 
Giuseppe Castagna <Giuseppe.Castagna@ens.fr>, Julien Demouth <Julien.Demouth@ens.fr>, and Stefano Zacchiroli <zack@di.ens.fr>. 
.\" created by instant / docbook-to-man, Fri 08 Jul 2005, 11:52 
