#!/usr/bin/env bash
#
# Runs a series of scripts that each check whether some code invariant
# is respected.
#

RULEDIR="tools/rules"

ERRORS=0

for script in $(find $RULEDIR -maxdepth 1 -perm -111 -type f); do
    # Only run the script if it is under revision control.
    git ls-files --error-unmatch "$file" > /dev/null 2>&1 # Returns 1 when the file is untracked.
    if [[ $? -eq 0 ]]; then
        echo "Running '$script'..."
        /usr/bin/env bash $script | sed 's/^/  - /'
        ERRORS=$(($ERRORS+$?))
    fi
done

exit $ERRORS
