#!/usr/bin/env bash
#
# Runs a series of scripts that each check whether some code invariant
# is respected.
#

RULEDIR="tools/rules"

for script in $(find $RULEDIR -maxdepth 1 -perm -111 -type f); do
    echo "Running '$script'..."
    /usr/bin/env bash $script | sed 's/^/  - /'
done
