#!/usr/bin/env bash
#
# Runs a series of scripts that each check whether some code invariant
# is respected.
#

RULEDIR="tools/rules"

ERRORS=0

for script in $(find $RULEDIR -maxdepth 1 -perm -111 -type f -not -name "*~"); do
    # Only run the script if it is under revision control.
    git ls-files --error-unmatch "$script" > /dev/null 2>&1 # Returns 1 when the file is untracked.
    if [[ $? -eq 0 ]]; then
        echo "Running '$script'..."
        /usr/bin/env bash $script | sed 's/^/  - /' ; test ${PIPESTATUS[0]} -eq 0
        ret_code=$?
        if [[ $ret_code -ne 0 ]]; then
            ERRORS=$(($ERRORS+$ret_code))
        fi
    fi
done

exit $ERRORS
