(defvar src "nim-slides.links")

(bufshow-start
 [("nim-slides.links" "header")
  ("nim-slides.links" "aboutme")
  ("nim-slides.links" "disclaimer")
  ("nim-slides.links" "motivation")
  ("nim-slides.links" "prologue")
  ("nim-slides.links" "choose")
  ("nim-slides.links" "coin-flip")
  ("nim-slides.links" "randomResult")
  ("nim-slides.links" "allResults")
  ("nim-slides.links" "generalised-choice")
  ("nim-slides.links" "whycare")
  ("nim-slides.links" "nim")
  ("nim-slides.links" "nim-rules")
  ("nim-slides.links" "player-model")
  ("nim-slides.links" "move")
  ("nim-slides.links" "aliceTurn")
  ("nim-slides.links" "game")
  ("nim-slides.links" "strategies")
  ("nim-slides.links" "perfect")
  ("nim-slides.links" "perfect-sugar")
  ("nim-slides.links" "strategy")
  ("nim-slides.links" "ps")
  ("nim-slides.links" "ms")
  ("nim-slides.links" "gamedata")
  ("nim-slides.links" "data-intro")
  ("nim-slides.links" "gametree")
  ("nim-slides.links" "cheat-detection")
  ("nim-slides.links" "cheat-strategy")
  ("nim-slides.links" "bobCheats")
  ("nim-slides.links" "cheat")
  ("nim-slides.links" "checker")
  ("nim-slides.links" "cheatReport")
  ("nim-slides.links" "combinators")
  ("nim-slides.links" "cheating-examples")
  ("nim-slides.links" "conclusion")
  ])
